### ISSUE TITLE
Max length for decimal numbers

### ISSUE THREAD

**Issue by scoumbourdis** [scoumbourdis/grocery-crud#141]
For more you can take a look at the post http://www.grocerycrud.com/forums/topic/1167-maxlength-of-decimal-fields/

**Comment by bvrignaud** [comment]
I have the same problem.
Why don't you apply the PR ?

**Comment by scoumbourdis** [comment]
Thanks @bvrignaud for the reminder. I did miss that.

Pull request merged with small changes to master: https://github.com/scoumbourdis/grocery-crud/pull/327

Closing this ticket. This will be released to public at the next version 1.5.3

Cheers
Johnny
