### ISSUE TITLE
Print columns issue please fix

### ISSUE THREAD

**Issue by icharge** [scoumbourdis/grocery-crud#309]
I've use Bootstrap theme  that I bought.

I attach picture for easy to understand.
![grocerybug](https://cloud.githubusercontent.com/assets/1619007/6650273/b2a01ae2-ca3b-11e4-8082-4fb4be3a4dd6.jpg)

**Comment by scoumbourdis** [comment]
Hello icharge, this is hapenning for all the themes. This is a grocery CRUD bug and not a theme specific bug. Can you please confirm?

Thanks
Johnny

**Comment by bvrignaud** [comment]
Hello,

I confirm his bug.

Looks the capture : 

1 : $config['grocery_crud_default_theme'] = 'flexigrid';
![flexigrid](https://cloud.githubusercontent.com/assets/9881829/6650598/b201d7b6-ca35-11e4-84a5-876ecd5cc4d2.png)
OK

2 : $config['grocery_crud_default_theme'] = 'bootstrap';
![bootstrap](https://cloud.githubusercontent.com/assets/9881829/6650600/cc4de4d4-ca35-11e4-8033-17763445e287.png)
NOK

**Comment by scoumbourdis** [comment]
Hello Benoit and thanks for the feedback. I will add it as a bug as a high priority for the theme and I will try to solve it soon. 

@Benoit, @icharge I will send you the new version with this bug fixed. 

By the way @bvrignaud I will also include the bug fix for the csrf protection for the print.

Thanks again for the feedback.
Johnny

**Comment by icharge** [comment]
@Johnny Please recheck this bug 
Thank you

**Comment by scoumbourdis** [comment]
@icharge I do confirm that this is a bug of the theme. I did check it by myself and you are right. I did add this bug as important and this will be fixed soon.

Thanks
Johnny

**Comment by scoumbourdis** [comment]
Hello @icharge . This bug is now fixed at the latest version of bootstrap theme (1.1.8) . Can you please send me an email to info@grocerycrud.com with your email address so I can send you the latest files?

Thanks
Johnny

**Comment by scoumbourdis** [comment]
Hello @icharge I did send you an email with the latest version of bootstrap theme (version 1.1.8) that it is fixing this issue.

Thanks
Johnny

**Comment by bvrignaud** [comment]
I think it's close now :-)
