### ISSUE TITLE
grocery_crud_dialog_forms not work in theme bootstrap

### ISSUE THREAD

**Issue by dyazincahya** [scoumbourdis/grocery-crud#316]
Hello johny,
grocery_crud_dialog_forms not work in theme premium bootstrap :(

**Comment by titu00** [comment]
Is this a bug or grocery_crud_dialog_forms are not supported on premium bootstrap?

**Comment by scoumbourdis** [comment]
Hello guys,

I am sorry but this is not a bug. The dialog_forms was (and still is) just an experiment for grocery CRUD and there are lot of unexpected issues on the JavaScript when you use it. That's the main reason that it wasn't included at bootstrap theme. It may be at a future release once the feature will not be as a BETA phase.

Thanks
Johnny
