### ISSUE TITLE
not support chinese language

### ISSUE THREAD

**Issue by vaisakh123** [scoumbourdis/grocery-crud#339]
not support chinese language in grocery-crud

**Comment by scoumbourdis** [comment]
Hello. It seems that the chinese IS supported by grocery CRUD. For more see: http://www.grocerycrud.com/documentation/options_functions/set_language 

There are some strings that are not translated yet but you can easy change that on the file: assets/grocery_crud/languages/chinese.php

If you do it so, please send me the file so we can update the file chinese.php and others to get the same support :)

Thanks
Johnny
