### ISSUE TITLE
callback_read_field

### ISSUE THREAD

**Issue by arpunpun** [scoumbourdis/grocery-crud#353]
Why there are no API for read field callback but in library have `callback_read_field`

> Can add callback_read_field in new version?

[REF!!!!!!!!!!!!!!!!!!!!!](http://www.grocerycrud.com/forums/topic/2525-callback-addedit-field-changes-the-display-on-the-read-method/#entry11240)

**Comment by moonvader** [comment]
same question - why there is no function for this?

**Comment by scoumbourdis** [comment]
Hello guys, I didn't do that on purpose :)

I will include it to the next version. I will let you know once this will be available. Anyone volunteering it to test it? 😄 

Regards
Johnny

**Comment by Akshay-Hegde** [comment]
`callback_read_field` - for read state (status code : 18), 
which will execute say you got url 

`http://yourhost.domain.com/controller/method/read/1`

Here is example code

```
/*
 You get  value, primary_key, field_info, field_values
*/
function _get_status($value, $primary_key, $field_info, $field_values)	
{   
   
   // see whats there
  // print_r(func_get_args()); die();

   $status = array('a' => 'alert-danger', 'b'=>'alert-success', 'c'=>'alert-info');
   return  '<div class="alert '.( isset($status[$value]) ? $status[$value] : 'alert-warning' ).'">'. $value .'</div>';     	
} 

function my_method()
{
$crud = new grocery_CRUD();
$crud->set_table('your_table');

$crud->callback_read_field('status',array($this,'_get_status'));


$output = $crud->render();
$this->_example_output($output);
}
```

**Comment by scoumbourdis** [comment]
This function is now ready to be used. You can either see the commit: https://github.com/scoumbourdis/grocery-crud/commit/34f2279e110877f22aef1f59065605be1bf9a74f either download the latest code from master in order to confirm that this is working.

If there is someone to confirm that it is working that would be great 😄
