### ISSUE TITLE
Bug using "unique_fields" on update

### ISSUE THREAD

**Issue by bvrignaud** [scoumbourdis/grocery-crud#357]
Hello and sorry for my English,

There is a bug when using unique_fields on update with a previous empty value.

For example :
MY_TABLE :
- ID = 1
- EMAIL = NULL (must be unique)

`$this->crud->unique_fields('EMAIL'); // failed !`

but :

MY_TABLE :
- ID = 1
- EMAIL = 'myname@something.com'

`$this->crud->unique_fields('EMAIL'); // OK`

**Comment by scoumbourdis** [comment]
Hello @bvrignaud I think the pull request here: https://github.com/scoumbourdis/grocery-crud/pull/453 is solving that issue
