### ISSUE TITLE
Help me all ::: SQL syntax error, prefix bug

### ISSUE THREAD

**Issue by dyazincahya** [scoumbourdis/grocery-crud#359]
how to fix "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.* FROM `d_pages` LIMIT 10' at line 1" ????

I use prefix table "d_" , and i use codeigniter 3.0.6 + grocery 1.5.4

Thanks before :)

**Comment by Nihilistik** [comment]
I gess u already fixed this or found a workaround. I link u here my solution:
https://github.com/Nihilistik/Grocery_CRUD-CodeIgniter-dbprefix-bug/

This solves the problem with 
`'.* FROM d_pages LIMIT 10'

and with

`SELECT d_'d_pages'.* FROM d_pages LIMIT 10`

Hope it helps!

**Comment by dyazincahya** [comment]
yes, I have to fix it here :)
https://github.com/scoumbourdis/grocery-crud/pull/360
.
problem solved :)
