### ISSUE TITLE
Bug fix: required_fields doesn't work for relation_n_n fields

### ISSUE THREAD

**Issue by scoumbourdis** [scoumbourdis/grocery-crud#38]
**Example:**
		$crud->set_relation_n_n('category', 'film_category', 'category', 'film_id', 'category_id', 'name');
		$crud->required_fields(['category']);

**Expected behaviour:** 
- When the Category field is empty then we should get an error that the Category is required
- When the Category field is not empty then we should not get any validation errors

**Actual Results:** 
- 👍  When the Category field is empty then it throws an error that the Category is required
- ❌ When the Category field is not empty then we are getting an error that the Category is required.

**Comment by scoumbourdis** [comment]
Re-opening as this is still an issue

**Comment by genya1** [comment]
Do you not not need to add that same piece of code into the db_update_validation for edit to properly validate n_n fields? I did that and then it worked for me in add and edit, this is the piece of code I am talking about:
```
					// Workaround as Codeigniter set_rules has a bug with array and doesn't work with required fields.
					// We are basically doing the check here!
					if (array_key_exists($field_name, $this->relation_n_n) && in_array($field_name, $required_fields)) {
						if (!array_key_exists($field_name, $_POST)) {
							// This will always throw an error!
							$this->set_rules($field_name, $field_types[$field_name]->display_as, 'required');
						}
					} else if(!isset($this->validation_rules[$field_name]) && in_array( $field_name, $required_fields) ) {
						$this->set_rules($field_name, $field_types[$field_name]->display_as, 'required');
					}
```

**Comment by scoumbourdis** [comment]
Closing issue as this is now fixed.

**Comment by vfonsecaz** [comment]
> Do you not not need to add that same piece of code into the db_update_validation for edit to properly validate n_n fields? I did that and then it worked for me in add and edit, this is the piece of code I am talking about:
> 
> ```
> 					// Workaround as Codeigniter set_rules has a bug with array and doesn't work with required fields.
> 					// We are basically doing the check here!
> 					if (array_key_exists($field_name, $this->relation_n_n) && in_array($field_name, $required_fields)) {
> 						if (!array_key_exists($field_name, $_POST)) {
> 							// This will always throw an error!
> 							$this->set_rules($field_name, $field_types[$field_name]->display_as, 'required');
> 						}
> 					} else if(!isset($this->validation_rules[$field_name]) && in_array( $field_name, $required_fields) ) {
> 						$this->set_rules($field_name, $field_types[$field_name]->display_as, 'required');
> 					}
> ```

yes, editing it's still giiving error without this fix! 
thanks
