### ISSUE TITLE
Search not working on bootstrap template

### ISSUE THREAD

**Issue by heruprambadi** [scoumbourdis/grocery-crud#386]
It happened with bootstrap premium template. Search by column is working. But the one on the right side print button is not work.
Strange.. it works on demo. Anyone can help ?

**Comment by scoumbourdis** [comment]
That's very strange. Are you sure that this is a bootstrap theme bug? Did you try it with flexigrid (default theme) and try to search All?

**Comment by heruprambadi** [comment]
Oh, i see the problem here.
I try to made virtual column that doesnt exist on database table.
It shown the data, but it's not searchable.

Thank's, and sorry for misunderstanding :)
