### ISSUE TITLE
How is working

### ISSUE THREAD

**Issue by Jmos** [scoumbourdis/grocery-crud#399]
Hello
I tried grocery crud but i run in trouble.
- set_table don't like underscore in table name
- with out set_table function all working when controller action same as table name with or with out underscore
is it a feature or bug?
best regards

**Comment by Kaabi** [comment]
@Jmos in all my projects using GC I'm using underscores in MySQL Tables names for over 5 years and never occurred anything like you just mentioned.

**Comment by scoumbourdis** [comment]
Closing as not defect
