### ISSUE TITLE
export only open new widow evet works

### ISSUE THREAD

**Issue by mckaygerhard** [scoumbourdis/grocery-crud#406]
i updated GC over CI 2.X and when i try to export now does'n work.. 

when button click, a new tab/window its open, i try to debug wuith chrome and f12 and javascript or network does not registrer nothing wrong

the error log does not register any error,

**Comment by mckaygerhard** [comment]
due the issue #407 the export also are afected, if a where filter or a like filter are set.. 

all the export funtions are totally broken if any filter are applied

**Comment by mckaygerhard** [comment]
i have an idea, set "soffice --headless --convert-to ods -outdir" with a custom query maybe work, the query results must be extracted from the grocery crud to do not be afected by the previous issues like the where/like limits of GC

**Comment by scoumbourdis** [comment]
Hello @mckaygerhard 

For which theme are you referring to? I guess flexigrid right?

Thanks
Johnny

**Comment by mckaygerhard** [comment]
for the flexigrid and the bootstrap, the datatables does not sufer of this issue due seems the data are taken from the front.. by the flash.. so datatables must be rewrite to implement the new functions in flexigrid

please read the firts intry and the issue #407 about more details due the implict of where/like also see the issue #396 due are same behaviour.....

**Comment by scoumbourdis** [comment]
Solving this issue for flexigrid with the last commit. Closing the ticket.
