### ISSUE TITLE
Webiste - db issues

### ISSUE THREAD

**Issue by r1800** [scoumbourdis/grocery-crud#424]
Hi,

Got the following error when trying to access the forums. 
Cheers
R

www.grocerycrud.com Driver Error
There appears to be an error with the database.
If you are seeing this page, it means there was a problem communicating with our database. Sometimes this error is temporary and will go away when you refresh the page. Sometimes the error will need to be fixed by an administrator before the site will become accessible again. 

You can try to refresh the page by clicking here

**Comment by scoumbourdis** [comment]
Again? :(

Ok. I will fix it asap. In few minutes you will have it back.

Regards
Johnny

**Comment by r1800** [comment]
Thanks Johnny. I have experience with LAMP stack and/or linux VM deployment so if you need a hand let me know.

**Comment by scoumbourdis** [comment]
Hello @r1800,

It is just time to move hosting :)

I will let you know once I will be on the migration period so maybe I will need a help. 

But for now, this is just some manual tickets of the hosting providers

Regards
Johnny

**Comment by r1800** [comment]
Sure, happy to help.

Regards
R

**Comment by scoumbourdis** [comment]
Problem solved. After hours of investigation did find the problem and fixed it. Sorry once again.

Regards
Johnny
