### ISSUE TITLE
Crud Requests Blocking By Adblock

### ISSUE THREAD

**Issue by mitulmlakhani** [scoumbourdis/grocery-crud#431]
The CRUD requests (add,update,delete) are blocking by adblock(i'm using [adblock plus)](adblockplus.org
) ad blocking extension. After disabling AdBlock it's working.

getting Error Message->An error has occurred on insert.

**Comment by scoumbourdis** [comment]
Hello @mitulmlakhani ,

Unfortunately I can't reproduce the issue and this is probably something in your template that is causing this issue. Usually another JavaScript is causing the issue and the JavaScript stops! So although it seems that the Grocery CRUD page fails this is something else. If you are sure that this is Grocery CRUD causing it please add more info at this ticket with the specific error and stack trace. Also if you have a public URL it will be also very helpful.

Regards
Johnny
