### ISSUE TITLE
Error in adding records

### ISSUE THREAD

**Issue by epatriciogh** [scoumbourdis/grocery-crud#449]
Hello, I am facing a problem with GC. I need to add some info to a table and I am getting the error:

500 (Internal Server Error)

This is the code I have in the controller:

function testdb(){
   $crud = new grocery_CRUD();
   $crud->set_theme('flexigrid');
   $crud->set_table('testdb');
   $crud->required_fields('A');
   $output = $crud->render();
   $output -> op = 'user_management';
 
   $this->_admin_output($output);
} 

My table testdb has only 3 feilds: id (INT), A(INT) and B(varchar 100) - mysql
 
When I remove the "$crud->required_fields('A');" I am able to save the data, but when I activate the required_field conditions the system returns 500 (Internal Server Error). I have checked logs for errors but 
nothing found. See attached file with error.

![image](https://user-images.githubusercontent.com/33767377/40209231-a92c1528-5a03-11e8-8490-db24a7a5ec69.png)

Can you help me?

Thanks for your help,

**Comment by epatriciogh** [comment]
Thanks, I tried to keep my code very simple just to find the problem. I have activated the debug options but i can not see any errors. I am almost a week trying to find the problem, please if you have any ideas it will be appreciated.

Thanks!

**Comment by portapipe** [comment]
If you have any URL where to debug the page send it to me in PM.
Anyway there shouldn't be any issue with that kind of action.
required_fields() use a codeigniter's standard function, so it's weird...

**Comment by epatriciogh** [comment]
Hi portapipe, I couldnt send the info in PM, I didnt find the option, so I prepared a test enviroment:
You can see in this link the controller with GC:
https://www.mitaxijj.com.ec/app/es/testc/testdb/

Controller code:
<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
class Testc extends CI_Controller {
	public function __construct()
    {
        parent:: __construct();
        $this->load->database();
		$this->load->helper('url');
		$this->load->library('grocery_CRUD');	
    }
   public function testdb(){
		$crud = new grocery_CRUD();
		$crud->set_theme('datatables');
		$crud->set_table('testdb');
		$crud->required_fields('A');
		$output = $crud->render();
		$output -> op = 'user_management';
	
		$this->_admin_output($output);
	}
	
function _admin_output($output = null)
	{
		$this->load->view('private/admin1.php',(array)$output);	
	}
}

View code:
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php 
foreach($css_files as $file): ?>
	<link type="text/css" rel="stylesheet" href="<?php echo $file; ?>" />
<?php endforeach; ?>
<?php foreach($js_files as $file): ?>
	<script src="<?php echo $file; ?>"></script>
<?php endforeach; ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body style="margin: 0;">
<?php echo $output; ?>
</body>
</html>

The table structure: 
3 feilds: id (INT), A(INT) and B(varchar 100) - mysql

Codeigniter version: const CI_VERSION = '3.1.8';
Grocery Crud version:  @version    	1.5.8

Hope you can help me and thanks.

**Comment by portapipe** [comment]
THIS is what I'm talking about good debugging:

```<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
<style type="text/css">

::selection { background-color: #E13300; color: white; }
::-moz-selection { background-color: #E13300; color: white; }

body {
	background-color: #fff;
	margin: 40px;
	font: 13px/20px normal Helvetica, Arial, sans-serif;
	color: #4F5155;
}

a {
	color: #003399;
	background-color: transparent;
	font-weight: normal;
}

h1 {
	color: #444;
	background-color: transparent;
	border-bottom: 1px solid #D0D0D0;
	font-size: 19px;
	font-weight: normal;
	margin: 0 0 14px 0;
	padding: 14px 15px 10px 15px;
}

code {
	font-family: Consolas, Monaco, Courier New, Courier, monospace;
	font-size: 12px;
	background-color: #f9f9f9;
	border: 1px solid #D0D0D0;
	color: #002166;
	display: block;
	margin: 14px 0 14px 0;
	padding: 12px 10px 12px 10px;
}

#container {
	margin: 10px;
	border: 1px solid #D0D0D0;
	box-shadow: 0 0 8px #D0D0D0;
}

p {
	margin: 12px 15px 12px 15px;
}
</style>
</head>
<body>
	<div id="container">
		<h1>An Error Was Encountered</h1>
		<p>Unable to load the requested language file: language/spanish/form_validation_lang.php</p>	</div>
</body>
</html>```

**Comment by epatriciogh** [comment]
Man you are great!, i just found the error you posted in firefox, i was missing the spanish package.
Thanks!

**Comment by portapipe** [comment]
😉

**Comment by scoumbourdis** [comment]
Thanks @portapipe for the help. I guess I can close the ticket now :)
