### ISSUE TITLE
Please use property_exists on this line!

### ISSUE THREAD

**Issue by Pimnr47** [scoumbourdis/grocery-crud#451]
https://github.com/scoumbourdis/grocery-crud/blob/b1b7cf4efd33f7760e0469b3afea57b8ce336637/application/libraries/Grocery_CRUD.php#L856

Hi John, please change to use property_exists instead of isset.

Isset breaks when my value is null, but has to be unique when filled. I have a table with a field that is null unless I fill it, then it should be unique. Current Isset on this line breaks that.

Thnx.

**Comment by scoumbourdis** [comment]
Hello @Pimnr47,

I can't reproduce this issue. Can you please specify:

Codeigniter version:
PHP version:
MySQL version:

For me it doesn't make sense to break so I guess this is maybe an issue with the PHP version? Also can you please write the error that you are getting?

Regards
Johnny

**Comment by scoumbourdis** [comment]
I see what you mean and you are completely right! I didn't know that to be honest. I will implement this change for the next version.

Regards
Johnny

**Comment by scoumbourdis** [comment]
This change is now in place with the pull request: https://github.com/scoumbourdis/grocery-crud/pull/453
