### ISSUE TITLE
Reduction of columns theme bootstrap grocery crud

### ISSUE THREAD

**Issue by elvisd027** [scoumbourdis/grocery-crud#460]
Hi, I have the bootstrap theme installed in grocery crud, every time I reduce the screen or see it from the phone, columns are hidden as the screen gets narrower. How can I do if I want to keep the columns as with the flexigrid theme, with a horizontal scroll but in bootstrap?

**Comment by portapipe** [comment]
You can try with some CSS.
Take a look at the inspector of your browser and check out the table-responsive class on the GC table.
You can play with some values :)
Plus If you know javascript you can remove that class dynamically and you're done.

**Comment by elvisd027** [comment]
Thank you very much, I actually got into the file list.css that is in themes / bootstrap / css / and modify the css styles where all the columns are visible from any screen. Greetings.
