### ISSUE TITLE
datatables - update table fails after delete

### ISSUE THREAD

**Issue by tikky** [scoumbourdis/grocery-crud#469]
I am using Grocery CRUD (v 1.6.2) with the standard theme (flexigrid).
Now I've switched to a new theme by: $crud->set_theme('datatables');

Everything looks fine, however, when I am deleting a record, the record is still visible in a list ( but should disappear - is deleted). After manual page refresh table is ok, without deleted record.

So looks like it is a problem with ajax refresh after delete.
In flexigrid works as expected.

**Comment by scoumbourdis** [comment]
I can reproduce the issue and this is a bug. Thank you for reporting this! I will try to fix it for the next version

**Comment by scoumbourdis** [comment]
This issue is now fixed
