### ISSUE TITLE
Wrong Ajax URL

### ISSUE THREAD

**Issue by karamelikli** [scoumbourdis/grocery-crud#479]
I am using Crud Grocery. After loading page any action could not be run. Firefox debugger shows http://localhost.com/CodeIgniter-3.1.7/index.php/CodeIgniter-3.1.7/index.php/Examples/filmm_anagement/ajax_list 404 error page. My codeigniter base url is /CodeIgniter-3.1.7 .

**Comment by scoumbourdis** [comment]
Your base_url should be: 
 http://localhost.com/CodeIgniter-3.1.7/ instead. You can also see some common mistakes on the installation of grocery CRUD here: https://www.youtube.com/watch?v=X0gnDD0qTS8&ab_channel=HappyDevelopers

Regards
Johnny

**Comment by karamelikli** [comment]
Problem solved. Thanks for your great project and great support.

**Comment by scoumbourdis** [comment]
Thank you sir. Glad that it worked for you :)
