### ISSUE TITLE
Adding more custom parameters at all the callbacks

### ISSUE THREAD

**Issue by scoumbourdis** [scoumbourdis/grocery-crud#48]

**Comment by bvrignaud** [comment]
Hello john,

An idea with Anonymous functions :
```php
$var = 'something';
$crud->callback_column('my_column', function($value, $row) use ($var) {
    return "this is just an example with $var"; 
});
```

**Comment by scoumbourdis** [comment]
Very true @bvrignaud ,

Closing this issue by the way as well :)

Now people can find a solution in their google search ;-)

**Comment by bvrignaud** [comment]
I think it could be useful to add this in your documentation.

**Comment by sahuadarsh0** [comment]
$client=$this->input->post('client_id');


        // echo "<pre>";
        // print_r ($client_id);  //data is recieved 1001
        // echo "</pre>";
        // die();

   $crud->callback_field('client_id', function ($value,$primary_key) use ($client_id){
            return $client_id; // returned nothing
        });


Not working with post data
data is received from post but not returned if used callback
