### ISSUE TITLE
Are there any future plans to update for CodeIgniter 4 ?

### ISSUE THREAD

**Issue by Eyad-Mohammed-Osama** [scoumbourdis/grocery-crud#485]
CodeIgniter 4 has been released since several days, are you guys planning to update Grocery CRUD to comply with the new release of CI ?

**Comment by scoumbourdis** [comment]
Hello @Eyad-Mohammed-Osama ,

Yes there is. I've already started a new repo for this: https://github.com/scoumbourdis/grocery-crud-codeigniter-4

Regards
Johnny
