### ISSUE TITLE
Update docs: callback_column

### ISSUE THREAD

**Issue by fireproofsocks** [scoumbourdis/grocery-crud#77]
You should mention explicitly that the callback function used by callback_column et al (http://www.grocerycrud.com/documentation/options_functions/callback_column) must be a public function -- private or protected functions will not work.  It would be good to show examples of using a standard helper function (i.e. a function NOT in a class) or a static function, e.g. 

```
$crud->callback_column('buyPrice', 'Examples::valueToEuro');

// ... later in your class...
/**
 * @param mixed $value
 * @param object $row
 * @return string
 */
static function valueToEuro($value, $row) {
// ...
}
```

Also note it would be super helpful if you added in some standard function documentation (a la JavaDoc)

**Comment by ontzuevanhussen** [comment]
Examples::valueToEuro()

For Indonesian Value?

**Comment by buoncri** [comment]
After writing something like this in your class
```
    $crud->callback_column('buyPrice', 'Examples::valueToIndonesianRupiah');
```
you can write a function like this, which provide the string you want to selected CG column
```
    function _valueToIndonesianRupiah($value, $row) {
        //return '<p align="right"> &euro; ' . $value . '</p>';
        if (is_null($value)) {
            return '<p align="right"> Rp 0.00 </p> ';
        } else {
            return '<p align="right">  Rp ' . $value . "</p>";
        }
    }
```
